name: Deploy Worker
on:
  push:
    branches: ["cloudflare/workers-autoconfig"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # Ensure your wrangler.json or wrangler.toml is in the root
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
